# Generated by Django 5.2.8 on 2025-11-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency_code',
            field=models.CharField(default='GHS', max_length=3),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='GH₵', max_length=5),
        ),
    ]
