# Generated by Django 5.2.8 on 2025-11-27 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional discount percentage for this customer (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
