# Generated by Django 5.2.8 on 2025-11-27 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_wholesale_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity for wholesale pricing'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale price for wholesale customers', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
